### PR TITLE
Update PuppeteerConnectionDelegate.js

### PR DESCRIPTION
**Pull request by SirLouen**
The Namespace was not fully changed so once I removed Nesk npm it start shooting errors

By the way, @xtrime-ru why don't you create an issue/discussion subtab in your repository

### CODE REVIEW

**Comment by xtrime-ru** [comment]
Thank you!

**Comment by SirLouen** [comment]
By the way @xtrime-ru I've noticed that a lot of Chrome defuct processes are popping everytime I call the puphpeteer object. 

I'm not sure if this is specific to puphpeteer, or to my code. Have you observed if this happening to you? I'm technically closing both page and browser after I'm done with the thing. But I feel that `$browser->close()` method is not doing anything

**Comment by xtrime-ru** [comment]
We using https://www.browserless.io docker containers. I dont know if there any zombie processes left. But we keep this containers running for years without restart, and they work ok. 

We use browser->close for local development like this: 

```php
if ($this->browser && $this->browser->isConnected()) {
	if ($this->remotePort === 0) {
		$this->browser->close();
	} else {
		$this->browser->disconnect();
	}
}
```

I suggest you to check who is parent of this zombie processes. You can find more info here: https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed

**Comment by SirLouen** [comment]
> I suggest you to check who is parent of this zombie processes. You can find more info here: https://askubuntu.com/questions/201303/what-is-a-defunct-process-and-why-doesnt-it-get-killed

I think I've found the issue, it's related to puppeteer straightly, not to puphpteer, because I transformed my PHP code into JS to run it straight with node and all those Zombie processes kept on popping, so I have moved the conversation to the github of puppeteer 

Anyway, @xtrime-ru consider opening the Issues tab in this repository in case anyone spots new bugs :)

Regards

**Comment by xtrime-ru** [comment]
Whoops. Done. No idea why it was disabled by default.

**Pull request merged**
