### PR TITLE
fix For "CdpPage.querySelector is not a function"

### PR DESCRIPTION
**Pull request by Raja-Omer-Mustafa**

### CODE REVIEW

**Comment by fnava621** [comment]
I have the same issue. 

I would greatly appreciate it if this could get merged. Thank you 😃

**Comment by Raja-Omer-Mustafa** [comment]
hey @fnava621 I notice this issue is fixed. I tested on my end. You can run composer update and if you are using supervisor you can restart supervisor to make it work.
I am going to close this issue

**Comment by sainthardrock** [comment]
i still getting same error "CdpPage.querySelector is not a function"

**Comment by sainthardrock** [comment]
i fixed on composer.json i moved from latest release to dev-zoon branch, @xtrime-ru i think it would be good if we can have a new release :smiley:

**Comment by xtrime-ru** [comment]
Made a release, thanks for remind.

**Pull request closed without merging**
